spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: <google client id>
            clientSecret: <google client secret>
            scope: email, public_profile
taco:
  orders:
    pageSize: 10
